{% set name = "colorful" %}
{% set version = "0.5.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{version}}.tar.gz
  sha256: bb16502b198be2f1c42ba3c52c703d5f651d826076817185f0294c1a549a7445 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - colorama  # [win]
    
test:
  source_files:
    - tests
  imports:
    - colorful
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: http://github.com/timofurrer/colorful
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Terminal string styling done right, in Python'
  description: |
    Terminal string styling done right, in Python.
    Key Features:
      * expressive and consistent API
      * support for different color modes (8 ANSI, 256 ANSI, true colors)
      * support for predefined awesome styles (solarized, ...)
      * support for custom color palettes
      * support nesting styles
      * support for different platforms (using colorama on Windows)
      * context managers for clean color mode, color palette or style switch
      * support len() on colored strings
      * support color names from X11 rgb.txt
      * no dependencies
  doc_url: https://github.com/timofurrer/colorful
  dev_url: https://github.com/timofurrer/colorful

extra:
  recipe-maintainers:
    - vnlitvinov
    - timofurrer
